### ISSUE TITLE
Basic example incorrect

### ISSUE THREAD

**Issue by Garito** [Fantomas42/mots-vides#1]
Hi!
Are you maintaining this library?
I've install it by doing:
pip install mots-vides

then I try your basic example with this error:
ImportError: cannot import name stop_words

I've tryed to install stop_words but the problem persists

Thanks!

**Comment by Fantomas42** [comment]
I have found an issue on the uploaded package on pypi,
but I cannot reproduce your issue.

Which line of the example fail ?

**Comment by Fantomas42** [comment]
Note I have just uploaded a new version on Pypi, correcting some packaging issues.

**Comment by Garito** [comment]
Thanks, will check it soon
